### ISSUE TITLE
Server Error from Exception with StringUtils

### ISSUE THREAD

**Issue by fastest963** [google/gitiles#140]
When navigating to certain repos, we just get "Server Error" and the logs show:
```[2018-06-04 17:44:15,024] [HTTP-316] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /plugins/gitiles/postmaster/+/master
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
at com.google.gitiles.doc.TocFormatter.idFromTitle(TocFormatter.java:228)
at com.google.gitiles.doc.TocFormatter.scan(TocFormatter.java:145)
at com.google.gitiles.doc.TocFormatter.scan(TocFormatter.java:119)
at com.google.gitiles.doc.TocFormatter.scan(TocFormatter.java:122)
at com.google.gitiles.doc.TocFormatter.setRoot(TocFormatter.java:52)
at com.google.gitiles.doc.MarkdownToHtml.renderToHtml(MarkdownToHtml.java:164)
at com.google.gitiles.doc.MarkdownToHtml.toSoyHtml(MarkdownToHtml.java:176)
at com.google.gitiles.ReadmeHelper.render(ReadmeHelper.java:101)
at com.google.gitiles.TreeSoyData.toSoyData(TreeSoyData.java:151)
at com.google.gitiles.TreeSoyData.toSoyData(TreeSoyData.java:161)
at com.google.gitiles.RevisionServlet.doGetHtml(RevisionServlet.java:107)
at com.google.gitiles.BaseServlet.doGet(BaseServlet.java:112)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
at com.google.gitiles.GitilesFilter$DispatchFilter$1.doFilter(GitilesFilter.java:157)
at com.googlesource.gerrit.plugins.gitiles.MenuFilter.doFilter(MenuFilter.java:58)
at com.google.gitiles.GitilesFilter$DispatchFilter$1.doFilter(GitilesFilter.java:155)
at com.google.gitiles.GitilesFilter$DispatchFilter.doFilter(GitilesFilter.java:160)
at com.google.gitiles.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31)
at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
at com.google.gitiles.ViewFilter.doFilter(ViewFilter.java:133)
at com.google.gitiles.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31)
at com.google.gitiles.ViewFilter.doFilter(ViewFilter.java:38)
at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
at com.google.gitiles.RepositoryFilter.doFilter(RepositoryFilter.java:50)
at com.google.gitiles.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31)
at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
at org.eclipse.jgit.http.server.glue.UrlPipeline.service(UrlPipeline.java:221)
at org.eclipse.jgit.http.server.glue.RegexPipeline.service(RegexPipeline.java:151)
at org.eclipse.jgit.http.server.glue.MetaFilter.doFilter(MetaFilter.java:178)
at org.eclipse.jgit.http.server.glue.MetaServlet.service(MetaServlet.java:134)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
```

This happens running the latest 2.15 build and running gitiles plugin from https://gerrit-ci.gerritforge.com/view/Plugins-stable-2.15/job/plugin-gitiles-bazel-stable-2.15/.

**Comment by gertvdijk** [comment]
FYI also happens on master for me currently. See [Gerrit Issue 9253](https://bugs.chromium.org/p/gerrit/issues/detail?id=9253).
